#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'Styling , testing and building your project before committing';
# run Prettier
npm run format

# check Prettier
npm run check-format ||
(
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again';
    false;
)

# Check ESlint
npm run check-lint ||
(
    echo 'ESlint Check Failed. Make the required changes listed above, add changes and try to commit again';
    false;
)

# Check tsconfig
npm run check-types ||
(
    echo 'Failed Type Check. Make the changes required above, add changes and try to commit again';
    false;
)

npm run build || 
(
    echo 'Your Build Failed, view the errors above';
    false;
)

echo 'Success Commit'
